@host = https://localhost:7246

###
POST {{host}}/backend/User
Content-Type: application/json

{
	"email": "plantastic@gmail.com",
	"password": "plantastic"
}

###
POST {{host}}/backend/User
Content-Type: application/json

{
	"email": "testing@gmail.com",
	"password": "test"
}

###
GET {{host}}/backend/User/1

###
POST {{host}}/backend/HomeStation/1
Content-Type: application/json

{
	"mac": "1234",
	"name": "Zuhause"	
}

###
POST {{host}}/backend/HomeStation/1
Content-Type: application/json

{
	"mac": "12345",
	"name": "Arbeit"	
}

###
GET {{host}}/backend/HomeStation/1

###
PUT {{host}}/backend/HomeStation
Content-Type: application/json

{
	"id": 2,
	"mac": "12345",
	"name": "Garten"	
}

###
DELETE {{host}}/backend/HomeStation/2

###
POST {{host}}/backend/Sensor
Content-Type: application/json

{
	"displayname": "Glücksfeder",
	"Mac": "2345",
	"Homestation": {
		"id": 1,
		"mac": "1234",
	"name": "Zuhause"	
	}
}

###
POST {{host}}/backend/Sensor
Content-Type: application/json

{
	"displayname": "Kaktus",
	"Mac": "23456",
	"Homestation": {
		"id": 1,
		"mac": "1234",
	"name": "Zuhause"	
	}
}

###
POST {{host}}/backend/SensorData
Content-Type: application/json

{
	"sensor": {
	"displayname": "Kaktus",
	"Mac": "23456",
	"Homestation": {
		"id": 1,
		"mac": "1234",
	"name": "Zuhause"	
	}},
	"Power": 13.2,
	"Moisture": 22.4,
	"Light": 143.6
}

###
GET {{host}}/backend/Sensor/1

###
PUT {{host}}/backend/Sensor
Content-Type: application/json

{	
	"SensorId": 1,
	"displayname": "Gluecksfeder",
	"mac": "2345",
	"plantType": 1,
	"HomeStation": {
		"mac": "1234",
	"name": "Zuhause"
	}
}