CREATE ROLE super WITH LOGIN PASSWORD 'super';

CREATE ROLE keycloak WITH LOGIN PASSWORD 'keycloak' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE keycloak_database;
GRANT ALL PRIVILEGES ON DATABASE keycloak_database TO keycloak;
GRANT ALL PRIVILEGES ON DATABASE keycloak_database TO super;

CREATE ROLE homestation WITH LOGIN PASSWORD 'homestation' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE homestation_database;
GRANT ALL PRIVILEGES ON DATABASE keycloak_database TO homestation;
GRANT ALL PRIVILEGES ON DATABASE keycloak_database TO super;

CREATE ROLE sensor WITH LOGIN PASSWORD 'sensor' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE sensor_database;
GRANT ALL PRIVILEGES ON DATABASE sensor_database TO sensor;
GRANT ALL PRIVILEGES ON DATABASE sensor_database TO super;
