version: "3"
services:
    database:
        image: "postgres:10.5"
        container_name: platastic-database
        ports:
            - "5432:5432"
        volumes:
            - ./db-init/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql
            - ~/databases/plantastic:/var/lib/postgresql/data/
    zookeeper:
        image: strimzi/kafka:0.11.3-kafka-2.1.0
        container_name: platastic-kafka-zookeeper
        command: [
            "sh", "-c",
            "bin/zookeeper-server-start.sh config/zookeeper.properties"
        ]
        ports:
            - "2181:2181"
        environment:
            LOG_DIR: /tmp/logs
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        container_name: platastic-keycloak
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: database
            DB_DATABASE: keycloak_database
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: keycloak
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
                  # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
                  #JDBC_PARAMS: "ssl=true"
        ports:
          - 8180:8080
        depends_on:
          - database
        
    kafka:
        image: strimzi/kafka:0.11.3-kafka-2.1.0
        container_name: platastic-kafka-broker
        command: [
            "sh", "-c",
            "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
        ]
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            LOG_DIR: "/tmp/logs"
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
