quarkus:
  # Enable to apply CORS filter
  http:
    cors: true
  # Datasource configuration
  oidc:
    auth-server-url: http://localhost:8180/auth/realms/plantastic
    client-id: plantastic-backend
    credentials:
      secret: 268f2ddf-6940-4518-841a-ba667f26112d
  log:
    level: INFO
    console:
      enable: true
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
      level: DEBUG
      color: true
    category:
      "org.hibernate":
        level: WARN
      "io.quarkus":
        level: INFO
#      "org.apache.kafka":
#        level: ERROR
# Your configuration properties
at:
  htl:
    superduperplantastic:
      sensor:
        service:
          SensorService/mp-rest/url: http://localhost:8084/
          SensorService/mp-rest/scope: javax.inject.Singleton
"%dev":
  quarkus:
    http:
      port: 8083
