quarkus:
  # Enable to apply CORS filter
  http:
    cors: true

  # Logging configuration
  log:
    level: INFO
    console:
      enable: true
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
      level: DEBUG
      color: true
    category:
      "org.hibernate":
        level: WARN
      "io.quarkus":
        level: INFO
#      "org.apache.kafka":
#        level: ERROR
keycloak-client:
  server-url: "http://localhost:8180/auth"
  "realm": "plantastic"
  "client-id": "admin-cli"
  "username": "quarkus"
  "password": "quarkus"

"%dev":
   quarkus:
     http:
       port: 8082
